Controllers/ProjectController.cs
using project.Models;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace project.Controllers
{
    [Authorize(Roles = "admin")]
    public class ProjectController : Controller
    {
        private ApplicationDbContext context;

        public ProjectController()
        {
            context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            context.Dispose();
        }

        // GET: Project
        public ActionResult Index()
        {
            var pros = context.Projects.Include(p => p.tasks);
            List<Models.project> projects = context.Projects.ToList();

            return View("Index", pros);
        }

        public ActionResult Details(int id)
        {
            //Models.project pro = context.Projects.SingleOrDefault(p => p.projectId == id);
            //Models.project pp =
            //    (from a in context.Projects join c in context.Tasks on a.projectId equals c.projectId select a)
            //    .SingleOrDefault();
            Models.project pro = context.Projects.Include(t => t.tasks).SingleOrDefault(p => p.projectId == id);
            return View("Details", pro);
        }

        [HttpPost]
        public ActionResult ProcessCreate(Models.project project)
        {
            Models.project pro = context.Projects.SingleOrDefault(p => p.projectId == project.projectId);
            if (pro != null)
            {
                pro.name = project.name;
                pro.description = project.description;
                pro.endDate = project.endDate;
            }
            else
            {
                context.Projects.Add(project);
            }
            context.SaveChanges();
            return Redirect("/project/index");
        }

        public ActionResult Edit(int id)
        {
            Models.project pro = context.Projects.SingleOrDefault(p => p.projectId == id);
            return View("EditForm", pro);
        }

        public ActionResult Create()
        {
            return View("EditForm", new Models.project());
        }

        public ActionResult Delete(int id)
        {
            Models.project pro = context.Projects.SingleOrDefault(p => p.projectId == id);
            if (pro != null)
            {
                context.Projects.Remove(pro);
                context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }


    }
}

Controllers/tasksController.cs
using Microsoft.AspNet.Identity;
using project.Models;
using System;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace project.Controllers
{
    [Authorize]
    public class tasksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: tasks
        public ActionResult Index()
        {
            var tasks = db.Tasks.Include(t => t.project).Include(t => t.user);
            return View(tasks.ToList());
        }

        // GET: tasks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tasks tasks = db.Tasks.Include(p => p.project).Include(u => u.user).SingleOrDefault(t => t.taskId == id);
            if (tasks == null)
            {
                return HttpNotFound();
            }
            return View(tasks);
        }

        // GET: tasks/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            ViewBag.projectId = new SelectList(db.Projects, "projectId", "name");
            ViewBag.userId = new SelectList(db.Users, "Id", "FirstName");
            return View();
        }

        // POST: tasks/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Create([Bind(Include = "taskId,name,description,startDate,endDate,workflow,type,projectId")] tasks tasks)
        {
            if (ModelState.IsValid)
            {
                db.Tasks.Add(tasks);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.projectId = new SelectList(db.Projects, "projectId", "name", tasks.projectId);
            ViewBag.userId = new SelectList(db.Users, "Id", "FirstName", tasks.userId);
            return View(tasks);
        }

        // GET: tasks/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tasks tasks = db.Tasks.Find(id);
            if (tasks == null)
            {
                return HttpNotFound();
            }
            ViewBag.projectId = new SelectList(db.Projects, "projectId", "name", tasks.projectId);
            ViewBag.userId = new SelectList(db.Users, "Id", "FirstName", tasks.userId);
            return View(tasks);
        }

        // POST: tasks/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit([Bind(Include = "taskId,name,description,startDate,endDate,workflow,type,projectId,userId")] tasks tasks)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tasks).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.projectId = new SelectList(db.Projects, "projectId", "name", tasks.projectId);
            ViewBag.userId = new SelectList(db.Users, "Id", "FirstName", tasks.userId);
            return View(tasks);
        }

        // GET: tasks/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tasks tasks = db.Tasks.Find(id);
            if (tasks == null)
            {
                return HttpNotFound();
            }
            return View(tasks);
        }

        // POST: tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            tasks tasks = db.Tasks.Find(id);
            db.Tasks.Remove(tasks);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult SelectTask(int id)
        {
            String currentUserId = User.Identity.GetUserId();
            ApplicationUser user = db.Users.Find(currentUserId);
            tasks task = db.Tasks.SingleOrDefault(t => t.taskId == id);

            if (task.userId == null)
            {
                task.user = user;
                db.Tasks.AddOrUpdate(task);
                db.SaveChanges();
            }
            else
            {
                ViewBag.SelectErreur = "Task" + id + " already taken by " + user.UserName;
            }

            return View("Details", task);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <style>


        body {
            height: 100%;
            overflow-x: hidden;
            font-family: 'Roboto', sans-serif;
            font-size: 16px;
        }


        #viewport {
            padding-left: 250px;
            -webkit-transition: all 0.5s ease;
            -moz-transition: all 0.5s ease;
            -o-transition: all 0.5s ease;
            transition: all 0.5s ease;
        }

        #sidebar {
            height: 100%;
            width: 250px;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #111;
            overflow-x: hidden;
            padding-top: 100px;
        }

            #sidebar header {
                font-size: 22px;
                line-height: 52px;
                text-align: center;
            }

                #sidebar header a {
                    color: #fff;
                    display: block;
                    text-decoration: none;
                }

                    #sidebar header a:hover {
                        color: #fff;
                    }

        #footer a {
            font-size: 30px;
            color: brown;
        }

        #btn1 {
            background-color: #2A265F;
            border: 0;
            border-radius: 50px;
            box-shadow: 0 10px 10px rgba(0, 0, 0, 0.2);
            color: #fff;
            font-size: 16px;
            padding: 12px 25px;
            position: absolute;
            bottom: 30px;
            right: 30px;
            letter-spacing: 1px;
        }

        #sidebar p {
            height: 65px;
            position: center;
            padding-top: -20em;
            font-size: 20px;
        }
    </style>

</head>

<div id="viewport">

    <div id="sidebar">
        <div class="header">
            @if (Request.IsAuthenticated)
            {
                using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                {
                    @Html.AntiForgeryToken()


                    <p> @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage")</p>

                }


            }
        </div>
        <header>
            <a href="#">
                <span>@Html.ActionLink("Home", "Index", "Home")</span>
            </a>
            <a href="#">
                <span> @Html.ActionLink("À propos de", "About", "Home") </span>
            </a>
            <a href="#">
                <span>@Html.ActionLink("Projects", "Index", "Project")</span>
            </a>
            <a href="#">
                <span> @Html.ActionLink("Tasks", "Index", "tasks")</span>
            </a>
        </header>
        <div id="footer">
            @if (Request.IsAuthenticated)
            {
                using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                {
                    @Html.AntiForgeryToken()
                    <button class="btn btn-outline-info" id="btn1" href="javascript:document.getElementById('logoutForm').submit()">Se déconnecter</button>
                }

            }
        </div>
    </div>


    <div id="content">

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Nourchen Ben Abdallah - Ayari Taha &copy;</p>
            </footer>
        </div>


    </div>

</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)